### ISSUE TITLE
What happens to timer signals that haven't expired yet?

### ISSUE THREAD

**Issue by getify** [shaseley/abort-signal-any#3]
The explainer has this example:

```js
// Picking up from the previous example, this is a skeleton for getting data
// for the tile.
async function getTileContents(tile, signal) {
  const signalWithTimeout = AbortSignal.any([signal, AbortSignal.timeout(10_000)]);
  const response = await fetch(tile.url, {signal: signalWithTimeout});
  return response.json();
}
```

What happens if an `AbortSignal.timeout(..)` timeout-signal has yet to fire when another signal in the "any" race fires? Is that timeout still running?

In the browser, timers hanging out in the background are not that big of a concern, as they just silently hold a tiny bit of resources and eventually fire silently.

But a more frustrating pattern is when such mechanisms are used in a context different from a long-lived browser web page, such as in Node. If a Node process is ready to complete, but there's a timer still hanging in the background, the Node process hangs waiting for the timer to expire. That can be quite frustrating if you're doing Node programming, especially CLI programs or other such tools.

The [CAF](https://github.com/getify/CAF) tool that I maintain -- which wraps AbortController/signal instances to provide cancelable-async-functions for flow control purposes -- has [addressed this problem](https://github.com/getify/CAF#delays--timeouts) by adopting a behavior where it forcibly clears the timeout-based controller/signal if it's part of a flow-control that ends earlier than the timeout.

That's cleaner for resource management in the browser, but also prevents the unexpected hanging of the otherwise-finished Node process.

I would encourage some careful thought about the implications of suggesting passing timer-based signals to "any" and whether there should be some automatic (or manual) facility for making sure those timers are cleaned up if the any-race finishes early. The automatic clearing of timers is something that I think users of CAF really appreciate, as it removes a complication they don't (and shouldn't) need to juggle.

But if this is not something where `any(..)` would automatically clear timer-signals (as CAF does), at a minimum I'd encourage mentioning this hanging-timers issue in the explainer when showing examples (like the one quoted above) where a long timer-signal is just vended for the purpose of an async call (like `fetch(..)`) but will just sit around in memory holding onto resources. If a page is making lots of those kinds of timer-attached calls, resources are getting held up unnecessarily, and it's not obvious to the programmer that they need to be cleaning them up manually.

Moreover, if this `any(..)` facility is eventually brought over to the Node world -- and I would expect it will -- then it would be better if the hanging-timer issue is at least documented ahead of time, as its implications for hanging Node processes becomes a much more visible/annoying problem.

**Comment by shaseley** [comment]
Thanks for filing the issue, considering the lifetime of timeout signals (and associated resources) is a good point.

This could be a problem now with `AbortSignal.timeout()` for "successful operations", independent of `AbortSignal.any()`. Do you know Node's implementation handled that case? Our (Chromium) implementation doesn't handle this yet, but I think it could.

I think this is something the UA should be able to handle &mdash; both in the successful operation case and other signal aborted case. At least in Chromium, we should be able to detect this and free the resources/deschedule the timer task. I just [wrote up](https://github.com/shaseley/abort-signal-any/blob/main/signal-memory-management.md) what I'm planning to prototype for signal memory management, and added a section at the end that addresses this. Basically, the idea is to hold things so that timeout signals can be GCed when we know they won't have an effect, and to cancel the timeout when that happens.

**Comment by getify** [comment]
I'm not aware of what Node is doing with this stuff, but I hope they're paying attention as well. :)

I will note that it's potentially a little "dangerous" to automatically clear timers (even ones vended via abort signals) via utilities like `any(..)`, because it's possible has created a single timer-abort-signal that they reuse for multiple `any(..)` calls.... just because one finishes doesn't mean you can safely discard the timer if the other one is still running.

Perhaps there's a way to "reference count" how many places a timer-abort-signal has been "listened to" and clean up once it goes away?

Or perhaps there's a way for the timers to be constructed "weakly" such that they automatically clear when any parent signal is GC'd?

Not sure, but I don't think this is stuff that userland can do very reliably. For CAF's case, I had to provide a `discard()` method on the token so that people could manually clean up such resources if they determine that the automatic cleanup CAF *does* perform is not quite sufficient.

**Comment by ghost** [comment]
It seems Node did handle it.

>Because the AbortSignal timeout cannot be canceled, we don't want the
>presence of the timer alone to keep the AbortSignal from being garbage
>collected if it otherwise no longer accessible. We also don't want the
>timer to keep the Node.js process open on it's own. Therefore, we wrap
>the AbortSignal in a WeakRef and have the setTimeout callback close
>over the WeakRef rather than directly over the AbortSignal, and we unref
>the created timer object. Separately, we add the signal to a
>FinalizerRegistry that will clear the timeout when the signal is gc'd.

This was there since it was first added in Dec 2021. https://github.com/nodejs/node/commit/722f113e0df6bab73a2cbd5e89a58099bf9ba0f4

I was glad to see it, thought I might have to write a custom replacement if these timeouts were stalling the process.
